/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 scene.gltf
Author: Dzhusi one (https://sketchfab.com/dzhusione)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/desert-road-48b076dadec243cbb7b7d7d37de097d3
Title: Desert road
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-43.28, 284.87, 0.71]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.body_body_0.geometry} material={materials.body} />
          <mesh geometry={nodes.body_body_0_1.geometry} material={materials.body} />
        </group>
        <group position={[-42.47, 109.27, 3.73]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.terrain_terrain_0.geometry} material={materials.terrain} />
          <mesh geometry={nodes.terrain_terrain_0_1.geometry} material={materials.terrain} />
        </group>
        <group position={[-43.28, 284.87, 0.71]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.body001outline_body001outline_0.geometry} material={materials.body001outline} />
          <mesh geometry={nodes.body001outline_body001outline_0_1.geometry} material={materials.body001outline} />
        </group>
        <group position={[-42.47, 109.27, 3.73]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.terrain001outline_terrain001outline_0.geometry} material={materials.terrain001outline} />
          <mesh geometry={nodes.terrain001outline_terrain001outline_0_1.geometry} material={materials.terrain001outline} />
        </group>
        <mesh geometry={nodes.sky_sky_0.geometry} material={materials.material} position={[-43.28, 284.87, 0.71]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.glass_glass_0.geometry} material={materials.glass} position={[-43.28, 284.87, 0.71]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object001_terrain001outline_0.geometry} material={materials.terrain001outline} position={[-42.47, 109.27, 3.73]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
