/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 seat.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/seat.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature003">
          <primitive object={nodes.Hips} />
          <skinnedMesh name="Wolf3D_Body003" geometry={nodes.Wolf3D_Body003.geometry} material={materials['Wolf3D_Body.005']} skeleton={nodes.Wolf3D_Body003.skeleton} />
          <skinnedMesh name="Wolf3D_Hair003" geometry={nodes.Wolf3D_Hair003.geometry} material={materials['Wolf3D_Hair.005']} skeleton={nodes.Wolf3D_Hair003.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Bottom003" geometry={nodes.Wolf3D_Outfit_Bottom003.geometry} material={materials['Wolf3D_Outfit_Bottom.005']} skeleton={nodes.Wolf3D_Outfit_Bottom003.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Footwear003" geometry={nodes.Wolf3D_Outfit_Footwear003.geometry} material={materials['Wolf3D_Outfit_Footwear.005']} skeleton={nodes.Wolf3D_Outfit_Footwear003.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Top003" geometry={nodes.Wolf3D_Outfit_Top003.geometry} material={materials['Wolf3D_Outfit_Top.005']} skeleton={nodes.Wolf3D_Outfit_Top003.skeleton} />
          <skinnedMesh name="EyeLeft003" geometry={nodes.EyeLeft003.geometry} material={materials['Wolf3D_Eye.005']} skeleton={nodes.EyeLeft003.skeleton} morphTargetDictionary={nodes.EyeLeft003.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft003.morphTargetInfluences} />
          <skinnedMesh name="EyeRight003" geometry={nodes.EyeRight003.geometry} material={materials['Wolf3D_Eye.005']} skeleton={nodes.EyeRight003.skeleton} morphTargetDictionary={nodes.EyeRight003.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight003.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Head003" geometry={nodes.Wolf3D_Head003.geometry} material={materials['Wolf3D_Skin.005']} skeleton={nodes.Wolf3D_Head003.skeleton} morphTargetDictionary={nodes.Wolf3D_Head003.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head003.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Teeth003" geometry={nodes.Wolf3D_Teeth003.geometry} material={materials['Wolf3D_Teeth.005']} skeleton={nodes.Wolf3D_Teeth003.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth003.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth003.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/seat.glb')
