/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 table.gltf
Author: abdullahyeahyea (https://sketchfab.com/abdullahyeahyea)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-gaming-desk-6f1bc394de704e488d44e77134f23993
Title: Low Poly Gaming Desk
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Table(props) {
  const { nodes, materials } = useGLTF('/models/Table/table.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.31}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.15, -2.84, -1.51]} scale={[1, 1, 0.88]}>
            <mesh castShadow geometry={nodes.Object_4.geometry} material={materials['Material.003']} />
            <mesh castShadow geometry={nodes.Object_5.geometry} material={materials.Plastic} />
          </group>
          <group position={[-0.91, 0.55, -1.55]} scale={[0.52, 0.1, 0.34]}>
            <mesh castShadow geometry={nodes.Object_7.geometry} material={materials['7355608']} />
            <mesh castShadow geometry={nodes.Object_8.geometry} material={materials.black} />
            <mesh castShadow geometry={nodes.Object_9.geometry} material={materials.blue_light} />
          </group>
          <group position={[-0.9, 0.47, -0.43]} rotation={[0, 0, -Math.PI]} scale={[-1.41, 0.02, 0.42]}>
            <mesh castShadow geometry={nodes.Object_11.geometry} material={materials.blue_light} />
            <mesh castShadow geometry={nodes.Object_12.geometry} material={materials.black} />
          </group>
          <group position={[0.79, 0.47, -0.78]} scale={[0.11, 0.11, 0.2]}>
            <mesh castShadow geometry={nodes.Object_14.geometry} material={materials.black} />
            <mesh castShadow geometry={nodes.Object_15.geometry} material={materials.blue_light} />
          </group>
          <group position={[-2.96, 1.46, -1.59]} scale={[0.44, 1, 1.09]}>
            <mesh castShadow geometry={nodes.Object_17.geometry} material={materials.black} />
            <mesh castShadow geometry={nodes.Object_18.geometry} material={materials.blue_light} />
            <mesh castShadow geometry={nodes.Object_19.geometry} material={materials.Plastic} />
          </group>
          <group position={[0.89, 1.04, -1.68]} rotation={[-1.7, 0, Math.PI / 2]} scale={[-0.23, 0.04, 0.23]}>
            <mesh castShadow geometry={nodes.Object_21.geometry} material={materials.black} />
            <mesh castShadow geometry={nodes.Object_22.geometry} material={materials.blue} />
          </group>
          <group position={[0.71, 0.47, -0.75]} scale={0.58}>
            <mesh castShadow geometry={nodes.Object_24.geometry} material={materials.Plastic} />
            <mesh castShadow geometry={nodes.Object_25.geometry} material={materials.blue_light} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/table.gltf')
